#!/usr/bin/env python3
"""Generate conformance/matrix/operator cells — operator lowering across the
op × width/sign × wrapper grid where the path-parity / result-type bugs live
(Code-Red-2 Class C; see plan-code-red-2.md §3.3).

This is the TARGETED layer (the confirmed/predicted-gap sub-grids). The pairwise
sample of the broader binary product, and the aggregate `==`/`!=` `.error` cells,
are planned follow-ups (§3.3) — start with the unary sub-grid, which pins the
live `-x`-on-a-named-sub-word defect (plan-cr2-1 Round-2 finding 8: the unary-minus
arm gates on `TYP_INT` and never peels `TYP_NAMED`, emitting `sub i64 0, %i8`).

Unary sub-grid: `op {neg, bitnot} × type {i8 u8 i16 u16 i32 u32 i64 u64} ×
wrapper {plain, named}`. Assertion: the unary result equals the spec value at the
correct width (printed as `cast(int, …)`). The named sub-word `neg` cells are RED
(finding 8); `bitnot` is correct for named (its arm passes `TYP_NAMED` straight to
`llvmType`), so `bitnot/named` is a control proving the asymmetry.

Coordinate-addressed: matrix/operator/<op>/<wrapper>/<type>.bn (+ .expected).
Run: python3 conformance/gen-operator-matrix.py [--check].
"""

import os
import sys

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matrix", "operator")

# (type-name, signed, bit-width)
TYPES = [
    ("int8", True, 8), ("uint8", False, 8),
    ("int16", True, 16), ("uint16", False, 16),
    ("int32", True, 32), ("uint32", False, 32),
    ("int64", True, 64), ("uint64", False, 64),
]
X = 5  # operand


def cast_int(raw, width, signed):
    """The value `cast(int, v)` yields for a width-bit pattern `raw`.
    int is 64-bit: a 64-bit source reinterprets; a narrower source sign- or
    zero-extends per its signedness."""
    if width == 64:
        return raw - (1 << 64) if raw >= (1 << 63) else raw
    if signed:
        return raw - (1 << width) if raw >= (1 << (width - 1)) else raw
    return raw  # unsigned narrow: zero-extend, fits a positive int


def neg_raw(width):
    return (-X) % (1 << width)


def bitnot_raw(width):
    return ((1 << width) - 1) - X


OPS = [("neg", "-", neg_raw), ("bitnot", "~", bitnot_raw)]
WRAPPERS = ["plain", "named"]

HEADER = """package "main"

// GENERATED by conformance/gen-operator-matrix.py — do not edit by hand.
// operator matrix cell — {desc}.
// The unary result must equal the spec value at the operand's width. A named
// sub-word `neg` is the live defect (the MINUS arm doesn't peel TYP_NAMED).
// See ../README.md and plan-code-red-2.md §3.3 / plan-cr2-1 Round-2.

"""


def cells():
    for opname, opsym, rawfn in OPS:
        for wrapper in WRAPPERS:
            for tname, signed, width in TYPES:
                if wrapper == "named":
                    helpers = f"type T {tname}"
                    typ = "T"
                else:
                    helpers = ""
                    typ = tname
                body = [f"var x {typ} = {X}", f"var y {typ} = {opsym}x",
                        "println(cast(int, y))"]
                expected = [cast_int(rawfn(width), width, signed)]
                yield (os.path.join(opname, wrapper, tname), helpers, body, expected)


def render(rel, helpers, body):
    out = HEADER.format(desc=rel)
    if helpers:
        out += helpers + "\n\n"
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    return out


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for rel, helpers, body, expected in cells():
        n += 1
        bn = render(rel, helpers, body)
        exp = "".join(str(x) + "\n" for x in expected)
        full = os.path.join(DIR, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        for ext, content in ((".bn", bn), (".expected", exp)):
            path = full + ext
            old = None
            if os.path.exists(path):
                with open(path) as f:
                    old = f.read()
            if old != content:
                changed.append(os.path.relpath(path, os.path.dirname(DIR)))
                if not check:
                    with open(path, "w") as f:
                        f.write(content)
    if check:
        if changed:
            print("operator matrix out of date (run conformance/gen-operator-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("operator matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
