#!/usr/bin/env python3
"""Generate conformance/matrix/loop-leak cells — per-iteration native-stack
leaks from un-hoisted allocas in loop bodies.

THE CLASS.  A construct whose lowering emits an `alloca` (or otherwise grows
the native stack) inside a loop body — rather than at the function entry
block — allocates fresh stack every iteration and never reclaims it, so the
program SIGSEGVs (stack overflow) once the loop runs long enough.  The output
is CORRECT right up until the crash, so a value-correctness matrix never sees
it; the leak only shows up at scale.  This bit:
  - default-init managed aggregates (`var m @[]char`)         — OP_CONST_NIL
  - `var a [N]char = "..."` string→array copies               — OP_RODATA_ARRAY
  - box() of a scalar register                                — OP_BOX
(see claude-todo.md and the codegen alloca-hoist pre-pass in
pkg/binate/codegen/emit_debug.bn).

THE ASSERTION.  Each cell repeats a construct in a high-iteration loop and
then prints `42`.  On a backend that leaks per iteration the stack overflows
before the print, so stdout is empty / a SIGSEGV — the cell FAILs.  A correct
backend (and the VM, which never touches the native stack for these) prints
`42`.  Iteration counts target ~13 MB of attempted leak — over the common
8 MB stack, comfortably under the 64 MB ceiling — so a leak crashes
deterministically while a fixed backend completes in milliseconds (work per
iteration is tiny, so even ~1.5 M iterations run fast on every mode).

THE COMPLEMENT.  This matrix is the end-to-end half.  Its static sibling,
`conformance/check-alloca-hoist.py` (driver: scripts/check-alloca-hoist.sh),
asserts the underlying invariant — every alloca lives in its function's entry
block — over the whole corpus, catching the class at compile time for any
construct, not just the ones enumerated here.

Axes:  conformance/matrix/loop-leak/<construct>.bn
  construct: which aggregate-producing thing sits in the loop body (the
             leak-prone op families, plus hoisted "control" ops that must
             also stay leak-free).

Coordinate-addressed (path = identity); regeneration is idempotent and never
touches `.xfail.<mode>`.  Run: `python3 conformance/gen-loop-leak-matrix.py`.
"""

import os
import sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "matrix", "loop-leak")

# Each construct: (name, decls, body_stmts, iters).  body_stmts is the list
# of statements placed inside the `for` loop.  iters is chosen so a
# per-iteration leak of the construct's alloca overflows an 8 MB stack
# (~13 MB attempted) while a correct backend finishes fast.
CONSTRUCTS = [
    # --- leak-prone: OP_CONST_NIL (default-init managed aggregates) ---
    ("const-nil-mslice", "",
     ["var m @[]char", "sink(len(m))"], 420000),         # 32 B/iter
    ("const-nil-nested-mslice", "",
     ["var m @[]@[]char", "sink(len(m))"], 420000),       # 32 B/iter
    ("const-nil-funcval", "",
     ["var f @func(int) int", "sink(0)"], 840000),        # 16 B/iter
    ("const-nil-iface", "",
     ["var sp @Speaker", "sink(0)"], 840000),             # 16 B/iter
    # --- controls: a default-init plain struct / array lowers via
    #     OP_ALLOC, which the entry-block alloca has always hoisted; these
    #     guard against a regression there (they never leaked). ---
    ("alloc-bigstruct", "",
     ["var s Big", "sink(s.data[0])"], 6500),             # 2 KB OP_ALLOC
    ("alloc-bigarray", "",
     ["var a [256]int", "sink(a[0])"], 6500),             # 2 KB OP_ALLOC
    # --- leak-prone: OP_RODATA_ARRAY (string -> [N]char) ---
    # The array length must equal the literal length, so amplify via a
    # 64-char string ([64]char = 64 B/iter) rather than a big array.
    ("rodata-array", "",
     ['var a [64]char = "%s"' % ("0123456789abcdef" * 4),
      "sink(cast(int, a[0]))"], 210000),                  # 64 B/iter
    # (OP_BOX's `.tmp` leak is covered by the static checker — boxing
    # needs a per-iteration heap alloc and a tiny `.tmp`, so a runtime
    # stress cell would be heavy and slow; conformance/check-alloca-hoist
    # over the corpus catches it cleanly, e.g. cells 445 / 450.)
    # --- controls: hoisted ops + per-iteration heap that must stay bounded ---
    ("control-make-slice", "",
     ["var m @[]char = make_slice(char, 4)", "sink(len(m))"], 200000),
    ("control-string-mslice", "",
     ['var m @[]char = "hello"', "sink(len(m))"], 200000),
]

# Shared declarations every cell carries (sink + the Big struct + the
# Speaker interface used by const-nil-iface).
PRELUDE = (
    "func sink(n int) { }\n\n"
    "type Big struct {\n\tdata [256]int\n}\n\n"
    "interface Speaker {\n\tspeak() int\n}\n\n"
    "type Sp struct {\n\tn int\n}\n\n"
    "func (s @Sp) speak() int { return s.n }\n\n"
    "impl @Sp : Speaker"
)

HEADER = '''package "main"

import "pkg/builtins/testing"

// GENERATED by conformance/gen-loop-leak-matrix.py — do not edit by hand.
// loop-leak matrix cell — construct={name}.
// Repeats `{name}` in a high-iteration loop, then prints 42.  A backend that
// leaks native stack per iteration (an un-hoisted alloca in the loop body)
// SIGSEGVs before the print; a correct backend / the VM prints 42.  See
// ../../check-alloca-hoist.py and claude-todo.md.

'''


def render(name, decls, body, iters):
    out = HEADER.format(name=name)
    out += PRELUDE + "\n"
    if decls:
        out += "\n" + decls + "\n"
    out += "\nfunc main() {\n"
    out += "\tfor i := 0; i < %d; i++ {\n" % iters
    for ln in body:
        out += "\t\t" + ln + "\n"
    out += "\t}\n"
    out += "\ttesting.Println(42)\n"
    out += "}\n"
    return out


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for name, decls, body, iters in CONSTRUCTS:
        n += 1
        bn = render(name, decls, body, iters)
        full = os.path.join(OUT, name)
        os.makedirs(os.path.dirname(full + ".bn"), exist_ok=True)
        for ext, content in ((".bn", bn), (".expected", "42\n")):
            path = full + ext
            old = open(path).read() if os.path.exists(path) else None
            if old != content:
                changed.append(os.path.relpath(path, os.path.dirname(OUT)))
                if not check:
                    open(path, "w").write(content)
    if check:
        if changed:
            print("loop-leak matrix out of date:")
            for c in changed:
                print("  " + c)
            return 1
        print("loop-leak matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print("%d cells" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
