#!/usr/bin/env python3
"""Generate conformance/matrix/nested-index cells — field/element access through a
(possibly nested) array INDEX base (a path-parity family defect: [N][M]Struct
value-struct field access reads 0 and writes NOWHERE).

The defect: the field-selector read path and the field-write lvalue path both
resolve the element type via `getIndexElemType` (gen_access.bn), which handles an
IDENT or SELECTOR base but does NOT recurse a nested-index base `a[i][j]`. So for
`a[i][j].field` the type resolves to nil → the struct arm is skipped → the read
folds to const-0 and the write returns a nil lvalue (stores nowhere). The in-place
element pointer is actually available (`genIndexPtr` / `indexExprType` recurse);
only this one type-resolver was never taught the nested case.

Axes: `<op>/<shape>` where op = field (read+write a struct field through the
index) / whole (read+write the whole element) / scalar (a scalar element), and
shape = single-`[N]` vs nested-`[N][M]` × value-struct / managed-ptr. The single-
level and whole-element and scalar cells are CONTROLS (work today); the
nested-`[N][M]` × field cells are RED (the defect), on ALL backends (shared IR-gen).

Assertion: every field/element reads back its written value. Coordinate-addressed:
matrix/nested-index/<op>/<shape>.bn (+ .expected).
Run: python3 conformance/gen-nested-index-matrix.py [--check].
"""

import os
import sys

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matrix", "nested-index")

STRUCT_S = "type S struct {\n\ta int\n\tb int\n}"
BOX_MK = ("type Box struct {\n\tv int\n}\n\n"
          "func mkBox(n int) @Box {\n\tvar b @Box = make(Box)\n\tb.v = n\n\treturn b\n}")

# (relpath, helpers, body[list of statements], expected[list])
CELLS = [
    # --- field access through a SINGLE-level array index (controls — work today) ---
    ("field/single-value-struct", STRUCT_S,
     ["var a [2]S", "a[1].a = 7", "a[1].b = 8", "testing.Println(a[1].a)", "testing.Println(a[1].b)"], [7, 8]),
    ("field/single-managed-ptr", BOX_MK,
     ["var a [2]@Box", "a[1] = mkBox(7)", "testing.Println(a[1].v)"], [7]),

    # --- field access through a NESTED array index base `a[i][j].field` — the
    #     defect: getIndexElemType doesn't recurse the nested base, so the read
    #     folds to 0 and the write stores nowhere. RED, all backends. ---
    ("field/nested-value-struct", STRUCT_S,
     ["var a [1][2]S", "a[0][1].a = 7", "a[0][1].b = 8", "testing.Println(a[0][1].a)", "testing.Println(a[0][1].b)"], [7, 8]),
    ("field/nested-managed-ptr", BOX_MK,
     ["var a [1][2]@Box", "a[0][1] = mkBox(7)", "testing.Println(a[0][1].v)"], [7]),

    # --- controls that isolate the defect to {nested base} × {field selector} ---
    # whole-element read/write through a nested index (no field selector) works:
    ("whole/nested-value-struct", STRUCT_S,
     ["var a [1][2]S", "var w S", "w.a = 7", "a[0][1] = w", "var r S = a[0][1]", "testing.Println(r.a)"], [7]),
    # a scalar element through a nested index works:
    ("scalar/nested", "",
     ["var a [1][2]int", "a[0][1] = 7", "testing.Println(a[0][1])"], [7]),
]

HEADER = """package "main"

import "pkg/builtins/testing"

// GENERATED by conformance/gen-nested-index-matrix.py — do not edit by hand.
// nested-index matrix cell — {desc}.
// Field/element access through a (possibly nested) array index base must read
// back the written value. The nested-`[N][M]` × field cells are the defect
// (getIndexElemType doesn't recurse the nested base). See ../README.md.

"""


def render(rel, helpers, body):
    out = HEADER.format(desc=rel)
    if helpers:
        out += helpers + "\n\n"
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    return out


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for rel, helpers, body, expected in CELLS:
        n += 1
        bn = render(rel, helpers, body)
        exp = "".join(str(x) + "\n" for x in expected)
        full = os.path.join(DIR, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        for ext, content in ((".bn", bn), (".expected", exp)):
            path = full + ext
            old = None
            if os.path.exists(path):
                with open(path) as f:
                    old = f.read()
            if old != content:
                changed.append(os.path.relpath(path, os.path.dirname(DIR)))
                if not check:
                    with open(path, "w") as f:
                        f.write(content)
    if check:
        if changed:
            print("nested-index matrix out of date (run conformance/gen-nested-index-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("nested-index matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
