#!/usr/bin/env python3
"""Generate conformance/matrix/operator cells — operator lowering across the
op × width/sign × wrapper grid where the path-parity / result-type bugs live.

This is the TARGETED layer (the confirmed/predicted-gap sub-grids). The pairwise
sample of the broader binary product, and the aggregate `==`/`!=` `.error` cells,
are planned follow-ups — start with the unary sub-grid, which pins the
live `-x`-on-a-named-sub-word defect (the unary-minus arm gates on `TYP_INT` and
never peels `TYP_NAMED`, emitting `sub i64 0, %i8`).

Unary sub-grid: `op {neg, bitnot} × type {i8 u8 i16 u16 i32 u32 i64 u64} ×
wrapper {plain, named}`. Assertion: the unary result equals the spec value at the
correct width (printed as `cast(int, …)`). The named sub-word `neg` cells are RED
(finding 8); `bitnot` is correct for named (its arm passes `TYP_NAMED` straight to
`llvmType`), so `bitnot/named` is a control proving the asymmetry.

Coordinate-addressed: matrix/operator/<op>/<wrapper>/<type>.bn (+ .expected).
Run: python3 conformance/gen-operator-matrix.py [--check].
"""

import os
import sys

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matrix", "operator")

# (type-name, signed, bit-width)
TYPES = [
    ("int8", True, 8), ("uint8", False, 8),
    ("int16", True, 16), ("uint16", False, 16),
    ("int32", True, 32), ("uint32", False, 32),
    ("int64", True, 64), ("uint64", False, 64),
]
X = 5  # operand


# Modes whose `int` is 32-bit (ILP32).  A cell whose `cast(int, …)` print differs
# from the LP64 (64-bit-int) value gets a per-mode `.expected.<mode>` override.
ILP32_MODES = ["builder-comp_arm32_linux", "builder-comp_arm32_baremetal"]


def cast_int(raw, width, signed, int_width):
    """The value `testing.Println(cast(int, v))` yields, where v is a width-bit value with
    two's-complement pattern `raw` (0 <= raw < 2^width) and the given signedness,
    cast to a signed `int` of int_width bits.  A source at least as wide as int
    truncates to the low int_width bits; a narrower source sign- or zero-extends
    per its signedness.  The result is then read as a signed int_width integer."""
    if width >= int_width:
        pat = raw & ((1 << int_width) - 1)
    elif signed and raw >= (1 << (width - 1)):
        pat = (raw - (1 << width)) & ((1 << int_width) - 1)
    else:
        pat = raw
    return pat - (1 << int_width) if pat >= (1 << (int_width - 1)) else pat


def neg_raw(width):
    return (-X) % (1 << width)


def bitnot_raw(width):
    return ((1 << width) - 1) - X


OPS = [("neg", "-", neg_raw), ("bitnot", "~", bitnot_raw)]
WRAPPERS = ["plain", "named"]

HEADER = """package "main"

import "pkg/builtins/testing"

// GENERATED by conformance/gen-operator-matrix.py — do not edit by hand.
// operator matrix cell — {desc}.
// The unary result must equal the spec value at the operand's width. A named
// sub-word `neg` is the live defect (the MINUS arm doesn't peel TYP_NAMED).
// See ../README.md.

"""


def cells():
    for opname, opsym, rawfn in OPS:
        for wrapper in WRAPPERS:
            for tname, signed, width in TYPES:
                if wrapper == "named":
                    helpers = f"type T {tname}"
                    typ = "T"
                else:
                    helpers = ""
                    typ = tname
                body = [f"var x {typ} = {X}", f"var y {typ} = {opsym}x",
                        "testing.Println(cast(int, y))"]
                raw = rawfn(width)
                exp64 = [cast_int(raw, width, signed, 64)]
                exp32 = [cast_int(raw, width, signed, 32)]
                yield (os.path.join(opname, wrapper, tname), helpers, body,
                       exp64, exp32)


def compound_cells():
    """Compound-assign × lvalue-form: does a guard/fix on the `ident` lvalue
    (e.g. the overshift guard, `fa265629`) reach the field/index lvalue forms?
    The overshift cells (`x <<= 40` etc.) are the path-parity-sensitive ones; the
    `add` cells are controls that the lvalue forms work for compound-assign."""
    lvals = [
        ("ident", "", ["var L uint32 = {init}"], "L"),
        ("field", "type S struct {\n\tf uint32\n}", ["var s S", "s.f = {init}"], "s.f"),
        ("index", "", ["var a [2]uint32", "a[1] = {init}"], "a[1]"),
    ]
    # (opname, opsym, init, operand, spec-result)
    ops = [
        ("shl-overshift", "<<=", 1, 40, 0),    # count 40 >= width 32 -> spec 0
        ("shr-overshift", ">>=", 256, 40, 0),  # logical shift, overshift -> 0
        ("add", "+=", 10, 5, 15),              # control
    ]
    for opname, opsym, init, operand, expected in ops:
        for lvname, helpers, setup, ref in lvals:
            body = [s.format(init=init) for s in setup]
            body.append(f"{ref} {opsym} {operand}")
            body.append(f"testing.Println(cast(int, {ref}))")
            yield (os.path.join("compound", opname, lvname), helpers, body,
                   [expected], [expected])


def _relop(name, a, b):
    if name == "lt":
        return a < b
    if name == "gt":
        return a > b
    if name == "le":
        return a <= b
    return a >= b  # ge


def binary_rel_cells():
    """Relational op × operand-POSITION × signed width. The untyped-int literal
    on the LEFT of a signed operand must use a SIGNED comparison (`5 < x` for
    `x = -1` is false); the bug `b54c9fdf` fixed made it unsigned. The lit-left
    cells guard that fix; lit-right is the control. Signed operands only (the
    signedness is what the literal-position bug turns on)."""
    LIT = 5
    X = -1
    relops = [("lt", "<"), ("gt", ">"), ("le", "<="), ("ge", ">=")]
    for opname, opsym in relops:
        for pos in ("lit-left", "lit-right"):
            for tname in ("int", "int8"):
                if pos == "lit-left":
                    expr = f"{LIT} {opsym} x"
                    res = _relop(opname, LIT, X)
                else:
                    expr = f"x {opsym} {LIT}"
                    res = _relop(opname, X, LIT)
                body = [f"var x {tname} = {X}", f"testing.Println(cast(int, {expr}))"]
                rv = [1 if res else 0]
                yield (os.path.join("rel", opname, pos, tname), "", body, rv, rv)


def all_cells():
    for c in cells():
        yield c
    for c in compound_cells():
        yield c
    for c in binary_rel_cells():
        yield c


_IFACE_EQ = ("interface G {\n\tget() int\n}\n\n"
             "type I struct {\n\tv int\n}\n\n"
             "func (i *I) get() int {\n\treturn i.v\n}\n\n"
             "impl *I : G")

# (name, helpers, decl-a, decl-b, expected error substring). These types are
# NEVER comparable with `==`/`!=`; the cells regression-guard the reject.  A
# plain struct / array of comparable fields IS now comparable (lowered
# field/element-wise — see conformance/spec/13-expressions/015,016 and
# 07-types/044), so the aggregate reject cells use a struct / array that
# transitively CONTAINS a non-comparable (slice) field.
EQ_TYPES = [
    ("raw-slice", "", "var a *[]int", "var b *[]int", "slices cannot be compared"),
    ("managed-slice", "", "var a @[]int", "var b @[]int", "slices cannot be compared"),
    ("func-value", "func mk() int {\n\treturn 1\n}",
     "var a @func() int = mk", "var b @func() int = mk",
     "function values cannot be compared"),
    ("iface", _IFACE_EQ, "var a @G = make(I)", "var b @G = make(I)",
     "interface values cannot be compared"),
    ("struct", "type S struct {\n\tn int\n\tv @[]int\n}", "var a S", "var b S",
     "this struct is not comparable"),
    ("array", "", "var a [2]@[]int", "var b [2]@[]int",
     "this array is not comparable"),
]


def error_cells():
    for name, helpers, da, db, err in EQ_TYPES:
        body = [da, db, "var c bool = a == b", "testing.Println(cast(int, c))"]
        yield (os.path.join("eq-reject", name), helpers, body, err)


def render(rel, helpers, body):
    out = HEADER.format(desc=rel)
    if helpers:
        out += helpers + "\n\n"
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    return out


def _sync(path, content, changed, check):
    """Reconcile `path` to `content`; `content is None` means it must not exist.
    Records the relpath in `changed` when the on-disk state differs (for --check)."""
    old = None
    if os.path.exists(path):
        with open(path) as f:
            old = f.read()
    if content is None:
        if old is not None:
            changed.append(os.path.relpath(path, os.path.dirname(DIR)))
            if not check:
                os.remove(path)
        return
    if old != content:
        changed.append(os.path.relpath(path, os.path.dirname(DIR)))
        if not check:
            with open(path, "w") as f:
                f.write(content)


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for rel, helpers, body, exp64, exp32 in all_cells():
        n += 1
        bn = render(rel, helpers, body)
        s64 = "".join(str(x) + "\n" for x in exp64)
        s32 = "".join(str(x) + "\n" for x in exp32)
        full = os.path.join(DIR, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        _sync(full + ".bn", bn, changed, check)
        _sync(full + ".expected", s64, changed, check)
        # An ILP32 (arm32) override only where the 32-bit `int` print differs;
        # otherwise ensure no stale override lingers.
        override = s32 if s32 != s64 else None
        for mode in ILP32_MODES:
            _sync(full + ".expected." + mode, override, changed, check)
    for rel, helpers, body, err in error_cells():
        n += 1
        bn = render(rel, helpers, body)
        full = os.path.join(DIR, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        for ext, content in ((".bn", bn), (".error", err + "\n")):
            path = full + ext
            old = None
            if os.path.exists(path):
                with open(path) as f:
                    old = f.read()
            if old != content:
                changed.append(os.path.relpath(path, os.path.dirname(DIR)))
                if not check:
                    with open(path, "w") as f:
                        f.write(content)
    if check:
        if changed:
            print("operator matrix out of date (run conformance/gen-operator-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("operator matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
