#!/usr/bin/env python3
"""Generate conformance/matrix/scalar cells — sub-word & 64-on-32 scalar VALUE
correctness (Class 5 of the code-red taxonomy; see
explorations/plan-code-red.md §3.8 / §7.1b).

Each cell computes a sub-word arithmetic op whose true result OVERFLOWS the
width, then consumes it DIRECTLY with a width-sensitive right shift — no
intermediate sized variable, which would re-narrow it. On a backend that
narrows sub-word results to their width (LLVM) the shifted value is correct;
on one that leaves dirty upper bits in the host register (the bytecode VM and
the native backends — §3.8) it diverges. The `.expected` is the CORRECT
(narrowed) value; the buggy modes are xfailed (the fix is P2/P4).

Coordinate-addressed like the refcount matrix: the path is the identity, so
regeneration is idempotent and `.xfail.<mode>` markers (maintained by hand)
are never touched. Run: `python3 conformance/gen-scalar-matrix.py [--check]`.

Python now; intended to port to Binate (dogfood) later — see ../matrix/README.md.
"""

import os
import sys

SCALAR_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "matrix", "scalar")

WIDTHS = [8, 16, 32]          # sub-word on the 64-bit host
OPS = {"add": "+", "mul": "*"}
SIGN = "unsigned"            # the confirmed case; signed is a planned follow-up


def operands(op, width):
    """Operands whose `op` overflows the width, with a mid-range truncated
    result (so the shifted value has meaningful bits, not 0)."""
    m = 1 << width
    if op == "add":
        v = m - 64                       # a+b = 2m-128, overflows by ~1 bit
        return v, v
    if op == "mul":
        v = (3 * (1 << (width // 2))) // 2   # ~1.5 * 2^(W/2); product ~2.25*2^W
        return v, v
    raise ValueError(op)


def cell(op, width):
    a, b = operands(op, width)
    m = 1 << width
    shift = width // 2
    raw = (a + b) if op == "add" else (a * b)
    correct = (raw % m) >> shift          # narrowed, then shifted: fits in uint<W>
    sym = OPS[op]
    body = [
        f"var a uint{width} = {a}",
        f"var b uint{width} = {b}",
        # consume (a op b) DIRECTLY — a sized var would re-narrow it.
        f"println(cast(int, (a {sym} b) >> {shift}))",
    ]
    return body, [correct]


HEADER = """package "main"

// GENERATED by conformance/gen-scalar-matrix.py — do not edit by hand.
// Scalar matrix cell — op={op}, width={width}, sign={sign}.
// Value correctness for a sub-word op whose true result overflows the width,
// consumed directly by a width-sensitive shift: a backend that fails to narrow
// the result leaks dirty upper bits and diverges from the correct value here.
// See ../../../README.md and plan-code-red.md §3.8.

"""


def render(op, width):
    body, expected = cell(op, width)
    out = HEADER.format(op=op, width=width, sign=SIGN)
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    exp = "".join(str(x) + "\n" for x in expected)
    return out, exp


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    for op in OPS:
        for width in WIDTHS:
            bn, exp = render(op, width)
            d = os.path.join(SCALAR_DIR, op, str(width))
            os.makedirs(d, exist_ok=True)
            for ext, content in ((".bn", bn), (".expected", exp)):
                path = os.path.join(d, SIGN + ext)
                old = None
                if os.path.exists(path):
                    with open(path) as f:
                        old = f.read()
                if old != content:
                    changed.append(os.path.relpath(path, os.path.dirname(SCALAR_DIR)))
                    if not check:
                        with open(path, "w") as f:
                            f.write(content)
    if check:
        if changed:
            print("scalar matrix out of date (run conformance/gen-scalar-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("scalar matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{len(OPS)} ops x {len(WIDTHS)} widths ({SIGN})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
