#!/usr/bin/env python3
"""Generate conformance/matrix/readonly cells — the `readonly` type modifier as a
transparent wrapper (Code-Red-2 Class B; see explorations/plan-code-red-2.md §3.2).

`readonly`/`const` is a semantic-only wrapper (like TYP_ALIAS): it must be PEELED
by every code path that switches on Type.Kind to pick a representation. The read
path (gen_selector) and the method-dispatch router (check_method) don't peel it,
so a readonly-wrapped aggregate/iface silently reads literal-0 (value ops) or is
wrongly rejected (dispatch ops). This matrix sweeps {inner-shape × operation} so a
missed peel in any layer surfaces.

Assertion: a readonly view observes the SAME value as the corresponding
non-readonly access (value ops), and a non-mutating method/iface call on a
readonly receiver succeeds and matches the plain result (dispatch ops). Each cell
prints one int per lane.

Coordinate-addressed: matrix/readonly/<operation>/<shape>.bn (+ .expected).
Run: python3 conformance/gen-readonly-matrix.py [--check].
"""

import os
import sys

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matrix", "readonly")

STRUCT_S = "type S struct {\n\ta int\n\tb int\n}"
BOX = "type Box struct {\n\tv int\n}"
BOX_M = BOX + "\n\nfunc (b *Box) getV() int {\n\treturn b.v\n}"
IFACE_G = ("interface Getter {\n\tget() int\n}\n\n"
           "type Impl struct {\n\tv int\n}\n\n"
           "func (im *Impl) get() int {\n\treturn im.v\n}\n\n"
           "impl *Impl : Getter")

# Each cell: (relpath, helpers, body[list of statements], expected[list]).
CELLS = [
    # --- scalar controls (readonly of a scalar — no aggregate dispatch) ---
    ("scalar/int", "",
     ["var x int = 7", "var rx readonly int = x", "println(rx)"], [7]),
    ("scalar/named", "type Count int",
     ["var x Count = 7", "var rx readonly Count = x", "println(cast(int, rx))"], [7]),

    # --- field-read: a readonly view of a struct / ptr-to-struct must read the
    #     real field (RED: gen_selector falls through to literal-0) ---
    ("field-read/value-struct", STRUCT_S,
     ["var s S", "s.a = 7", "s.b = 8", "var rs readonly S = s",
      "println(rs.a)", "println(rs.b)"], [7, 8]),
    ("field-read/managed-ptr", BOX,
     ["var p @Box = make(Box)", "p.v = 7", "var rp readonly @Box = p",
      "println(rp.v)"], [7]),
    ("field-read/raw-ptr", BOX,
     ["var b Box", "b.v = 7", "var rb readonly *Box = &b", "println(rb.v)"], [7]),

    # --- index-read: a readonly array view ---
    ("index/array", "",
     ["var a [3]int", "a[0] = 7", "a[2] = 9", "var ra readonly [3]int = a",
      "println(ra[0])", "println(ra[2])"], [7, 9]),

    # --- method / iface dispatch on a readonly receiver (RED: check_method does
    #     not peel TYP_READONLY before the iface/struct method dispatch) ---
    ("method/managed-struct", BOX_M,
     ["var p @Box = make(Box)", "p.v = 7", "var rp readonly @Box = p",
      "println(rp.getV())"], [7]),
    ("method/iface", IFACE_G,
     ["var im @Impl = make(Impl)", "im.v = 7", "var r @Getter = im",
      "var rr readonly @Getter = r", "println(rr.get())"], [7]),

    # --- pass a value to a readonly parameter, read a field inside ---
    ("pass-arg/value-struct", STRUCT_S + "\n\nfunc readA(s readonly S) int {\n\treturn s.a\n}",
     ["var s S", "s.a = 7", "println(readA(s))"], [7]),

    # --- wrapper-ORDER: the modifier on the POINTEE (`@readonly Box` / `*readonly
    #     Box`), not the pointer (`readonly @Box`). The inner-pointee variants the
    #     outer-wrapper field-read fix (27c1ee8b) did not cover — gen_selector reads
    #     an un-peeled `.Elem`. (2026-06-08 review sibling; plan-cr2-1 Round-2.) ---
    ("wrapper-order/inner-managed-ptr", BOX,
     ["var m @Box = make(Box)", "m.v = 7", "var p @readonly Box = m", "println(p.v)"], [7]),
    ("wrapper-order/inner-raw-ptr", BOX,
     ["var b Box", "b.v = 7", "var p *readonly Box = &b", "println(p.v)"], [7]),

    # --- alias-typed receiver method dispatch (`type AB = @Box`): TYP_ALIAS not
    #     peeled at the method-lookup site (ReceiverBaseNamed). Sibling of the
    #     readonly-receiver dispatch fix. ---
    ("alias/method-receiver",
     BOX_M + "\n\ntype AB = @Box\n\nfunc mkBox(n int) @Box {\n\tvar b @Box = make(Box)\n\tb.v = n\n\treturn b\n}",
     ["var x AB = mkBox(7)", "println(x.getV())"], [7]),

    # --- construct a managed interface value through a `readonly` target
    #     (reject-only today — a concrete value can't be iface-wrapped into a
    #     readonly @Iface). ---
    ("construct/readonly-iface", IFACE_G,
     ["var im @Impl = make(Impl)", "im.v = 7", "var iv readonly @Getter = im", "println(iv.get())"], [7]),
]

HEADER = """package "main"

// GENERATED by conformance/gen-readonly-matrix.py — do not edit by hand.
// readonly matrix cell — {desc}.
// A readonly view must observe the same value / dispatch as the plain value;
// `readonly` is a transparent wrapper every Kind-dispatch must peel.
// See ../README.md and plan-code-red-2.md §2 (Class B) / §3.2.

"""


def render(rel, helpers, body):
    out = HEADER.format(desc=rel)
    if helpers:
        out += helpers + "\n\n"
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    return out


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for rel, helpers, body, expected in CELLS:
        n += 1
        bn = render(rel, helpers, body)
        exp = "".join(str(x) + "\n" for x in expected)
        full = os.path.join(DIR, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        for ext, content in ((".bn", bn), (".expected", exp)):
            path = full + ext
            old = None
            if os.path.exists(path):
                with open(path) as f:
                    old = f.read()
            if old != content:
                changed.append(os.path.relpath(path, os.path.dirname(DIR)))
                if not check:
                    with open(path, "w") as f:
                        f.write(content)
    if check:
        if changed:
            print("readonly matrix out of date (run conformance/gen-readonly-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("readonly matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
