#!/usr/bin/env python3
"""Generate conformance/matrix/scalar cells — sub-word & 64-on-32 scalar VALUE
correctness (Class 5 of the code-red taxonomy; see
explorations/plan-code-red.md §3.8 / §7.1b).

Each cell computes a sub-word arithmetic op whose true result OVERFLOWS the
width, then consumes it DIRECTLY with a width-sensitive right shift — no
intermediate sized variable, which would re-narrow it. On a backend that
narrows sub-word results to their width (LLVM) the shifted value is correct;
on one that leaves dirty upper bits in the host register (the bytecode VM and
the native backends — §3.8) it diverges. The `.expected` is the CORRECT
(narrowed) value; the buggy modes are xfailed (the fix is P2/P4).

Coordinate-addressed like the refcount matrix: the path is the identity, so
regeneration is idempotent and `.xfail.<mode>` markers (maintained by hand)
are never touched. Run: `python3 conformance/gen-scalar-matrix.py [--check]`.

Python now; intended to port to Binate (dogfood) later — see ../matrix/README.md.
"""

import os
import sys

SCALAR_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "matrix", "scalar")

WIDTHS = [8, 16, 32]          # sub-word on the 64-bit host
OPS = {"add": "+", "sub": "-", "mul": "*"}
SIGNS = ["unsigned", "signed"]


def operands(op, width, sign):
    """Operands whose `op` overflows/underflows the width, with a non-trivial
    truncated result."""
    m = 1 << width
    half = m >> 1
    if sign == "unsigned":
        if op == "add":
            return m - 64, m - 64             # overflow
        if op == "mul":
            v = (3 * (1 << (width // 2))) // 2
            return v, v
        if op == "sub":
            return m // 4, (3 * m) // 4        # underflow (a < b -> wraps)
    else:  # signed
        if op == "add":
            return half - 8, half - 8          # overflow past max -> negative
        if op == "mul":
            v = (3 * (1 << (width // 2))) // 2
            return v, v
        if op == "sub":
            return -half + 4, 100              # overflow below min
    raise ValueError(op)


def cell(op, width, sign):
    a, b = operands(op, width, sign)
    m = 1 << width
    half = m >> 1
    shift = width // 2
    raw = {"add": a + b, "sub": a - b, "mul": a * b}[op]
    t = raw % m                              # truncate to width
    if sign == "signed" and t >= half:
        t -= m                               # interpret as signed
    correct = t >> shift                     # Python >> is arithmetic for negative t
    sym = OPS[op]
    typ = ("int" if sign == "signed" else "uint") + str(width)
    body = [
        f"var a {typ} = {a}",
        f"var b {typ} = {b}",
        # consume (a op b) DIRECTLY — a sized var would re-narrow it.
        f"println(cast(int, (a {sym} b) >> {shift}))",
    ]
    return body, [correct]


HEADER = """package "main"

// GENERATED by conformance/gen-scalar-matrix.py — do not edit by hand.
// Scalar matrix cell — op={op}, width={width}, sign={sign}.
// Value correctness for a sub-word op whose true result overflows the width,
// consumed directly by a width-sensitive shift: a backend that fails to narrow
// the result leaks dirty upper bits and diverges from the correct value here.
// See ../../../README.md and plan-code-red.md §3.8.

"""


def render(op, width, sign):
    body, expected = cell(op, width, sign)
    out = HEADER.format(op=op, width=width, sign=sign)
    out += "func main() {\n"
    for ln in body:
        out += "\t" + ln + "\n"
    out += "}\n"
    exp = "".join(str(x) + "\n" for x in expected)
    return out, exp


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    for op in OPS:
        for width in WIDTHS:
            for sign in SIGNS:
                bn, exp = render(op, width, sign)
                d = os.path.join(SCALAR_DIR, op, str(width))
                os.makedirs(d, exist_ok=True)
                for ext, content in ((".bn", bn), (".expected", exp)):
                    path = os.path.join(d, sign + ext)
                    old = None
                    if os.path.exists(path):
                        with open(path) as f:
                            old = f.read()
                    if old != content:
                        changed.append(
                            os.path.relpath(path, os.path.dirname(SCALAR_DIR)))
                        if not check:
                            with open(path, "w") as f:
                                f.write(content)
    if check:
        if changed:
            print("scalar matrix out of date (run conformance/gen-scalar-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("scalar matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{len(OPS)} ops x {len(WIDTHS)} widths x {len(SIGNS)} signs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
