#!/usr/bin/env python3
"""Generate conformance/matrix/shift-typepair cells.

A shift `x << y` / `x >> y` is asymmetric: the count `y` may be ANY integer
type, independent of the value `x`, and the result type is the VALUE's.  This
matrix covers the full product of (value-type, count-type) and asserts:

  - PERMITTED: the shift compiles for every integer count type (it used to be
    rejected when the operand types differed — `int64 << int` in 32-bit-int
    modes — as "mismatched types").
  - RESULT TYPE = the value's: the result is bound to `var r <vtype>` with NO
    cast.  A result widened to the (wider) count's type would be a narrowing
    assignment and fail to COMPILE — so a cell that compiles already proves
    the result is no wider than the value.
  - VALUE: correct at the value's width — a small in-range case, plus (for
    fixed-width value types) an overshift case that pins the result WIDTH: an
    overshift at the value width yields 0 (logical) / sign-fill (arithmetic),
    which a wider-typed result would not produce.

Coordinate-addressed: conformance/matrix/shift-typepair/<op>/<vtype>.bn; the
count-type is the in-cell sweep dimension (like scalar-diff sweeps values).
Every line is `println(bi(<computed> == <spec>))` -> 1, so the cells are
target-stable.  The target-width value types (`int`/`uint`) skip the
overshift-width check (its result depends on the target int size); they still
assert permitted + result-type + small value.

Run: `python3 conformance/gen-shift-typepair-matrix.py [--check]`.
"""

import os
import sys

MATRIX_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "matrix", "shift-typepair")

# (name, bit-width or None for target-word-width, signed)
TYPES = [
    ("int8", 8, True), ("int16", 16, True), ("int32", 32, True),
    ("int64", 64, True), ("int", None, True),
    ("uint8", 8, False), ("uint16", 16, False), ("uint32", 32, False),
    ("uint64", 64, False), ("uint", None, False),
]
OPS = {"shl": "<<", "shr": ">>"}


def cell(op, vname, vwidth):
    """Return (body_lines, n_assertions) for the (op, value-type) cell."""
    body = []
    nprint = 0
    for i, (cname, _cwidth, _csigned) in enumerate(TYPES):
        body.append(f"\t// count type {cname}")
        # Permitted + result-type (no-cast bind) + small in-range value.
        if op == "shl":
            body += [
                f"\tvar va{i} {vname} = 3",
                f"\tvar na{i} {cname} = 2",
                f"\tvar ra{i} {vname} = va{i} << na{i}",
                f"\tprintln(bi(ra{i} == cast({vname}, 12)))",  # 3 << 2
            ]
        else:
            body += [
                f"\tvar va{i} {vname} = 12",
                f"\tvar na{i} {cname} = 2",
                f"\tvar ra{i} {vname} = va{i} >> na{i}",
                f"\tprintln(bi(ra{i} == cast({vname}, 3)))",  # 12 >> 2
            ]
        nprint += 1
        # Width-sensitivity: overshift at the value's width (fixed-width only).
        if vwidth is not None:
            if op == "shl":
                body += [
                    f"\tvar vb{i} {vname} = 1",
                    f"\tvar kb{i} {cname} = cast({cname}, {vwidth})",
                    f"\tvar rb{i} {vname} = vb{i} << kb{i}",
                    f"\tprintln(bi(rb{i} == cast({vname}, 0)))",  # overshift -> 0
                ]
            else:
                body += [
                    f"\tvar vb{i} {vname} = cast({vname}, 0) - cast({vname}, 1)",
                    f"\tvar kb{i} {cname} = cast({cname}, {vwidth})",
                    f"\tvar rb{i} {vname} = vb{i} >> kb{i}",
                ]
                # signed >> overshift sign-fills (-1); unsigned -> 0.
                # (-1 is the all-ones value just constructed.)
                _, _, vsigned = TYPES[[t[0] for t in TYPES].index(vname)]
                if vsigned:
                    body.append(
                        f"\tprintln(bi(rb{i} == "
                        f"(cast({vname}, 0) - cast({vname}, 1))))")
                else:
                    body.append(f"\tprintln(bi(rb{i} == cast({vname}, 0)))")
            nprint += 1
    return body, nprint


HEADER = (
    'package "main"\n'
    "\n"
    "// GENERATED by conformance/gen-shift-typepair-matrix.py "
    "— do not edit by hand.\n"
    "// shift-typepair matrix cell — op={op}, value-type={vname}.\n"
    "// A shift's count type is independent of the value type; the result\n"
    "// type is the value's.  Sweeps every integer count type.  Each line is\n"
    "// a target-stable 0/1 self-check.  See ../../README.md.\n"
    "\n"
    "func bi(b bool) int {{\n"
    "\tif b {{ return 1 }}\n"
    "\treturn 0\n"
    "}}\n"
    "\n"
    "func main() {{\n"
    "{body}\n"
    "}}\n"
)


def render(op, vname, vwidth):
    body, nprint = cell(op, vname, vwidth)
    bn = HEADER.format(op=op, vname=vname, body="\n".join(body))
    expected = "1\n" * nprint
    return bn, expected


def main():
    check = "--check" in sys.argv[1:]
    changed = []
    n = 0
    for op in OPS:
        for vname, vwidth, _vsigned in TYPES:
            n += 1
            bn, expected = render(op, vname, vwidth)
            d = os.path.join(MATRIX_DIR, op)
            os.makedirs(d, exist_ok=True)
            for ext, content in ((".bn", bn), (".expected", expected)):
                path = os.path.join(d, vname + ext)
                old = None
                if os.path.exists(path):
                    with open(path) as f:
                        old = f.read()
                if old != content:
                    changed.append(
                        os.path.relpath(path, os.path.dirname(MATRIX_DIR)))
                    if not check:
                        with open(path, "w") as f:
                            f.write(content)
    if check:
        if changed:
            print("shift-typepair matrix out of date "
                  "(run conformance/gen-shift-typepair-matrix.py):")
            for c in changed:
                print("  " + c)
            return 1
        print("shift-typepair matrix up to date")
        return 0
    for c in changed:
        print("wrote " + c)
    print(f"{n} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
